[project]
authors = ["lesoup-mxd <dulich.m@live.unic.ac.cy>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
